# Generated by Django 2.0.6 on 2019-10-31 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('nome_mae', models.CharField(max_length=30, verbose_name='Nome da Mãe')),
                ('fone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Amigo',
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('etiqueta', models.CharField(max_length=20, verbose_name='Etiqueta')),
                ('cor', models.CharField(max_length=12, verbose_name='Cor')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataemp', models.DateField(verbose_name='Data do emprestimo')),
                ('datadev', models.DateField(verbose_name='Data de devolução')),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Amigo')),
            ],
            options={
                'verbose_name_plural': 'Emprestimos',
                'ordering': ('-dataemp', 'revista'),
            },
        ),
        migrations.CreateModel(
            name='GrupoAmigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Grupo de Amigos',
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de Edição')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caixa')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Colecao')),
            ],
            options={
                'verbose_name_plural': 'Revistas',
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='grupo_amigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoAmigo'),
        ),
    ]
